
ALTER TABLE roles ADD COLUMN IF NOT EXISTS estado VARCHAR(20) DEFAULT 'activo';
ALTER TABLE roles ADD COLUMN IF NOT EXISTS fecha_control TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS usuario_control INTEGER REFERENCES usuarios(id);
